name: ms_datetime_extensions
description: A new Flutter package project.
version: 0.1.0
homepage: marcussoftware.info

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

