name: ms_datetime_extensions
description: A simple and usefull lib to incremease DateTime with usefull functions
version: 0.3.0
homepage: https://github.com/Marcus-Software/ms_datetime_extensions

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0

dev_dependencies:
  test: ^1.9.2
